spring:
  datasource:
    initialization-mode: always
    url: jdbc:h2:~/ser-for;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    data: classpath:data-sql-dev.sql

  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect

  liquibase:
    change-log: classpath:liquibase/liquibase-changeLog.xml
    enabled: true
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

  h2:
    console:
      enabled: true

