spring:
  datasource:
    initialization-mode: always
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/ser-for;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:

  profiles:
    active: production